ARG BASE_REGISTRY=registry1.dsop.io
ARG BASE_IMAGE=redhat/ubi/ubi9
ARG BASE_TAG=9.6

FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG} as prep_files
ARG ELASTIC_STACK={{ beat_version }}
ARG ELASTIC_PRODUCT=elastic-agent
