name: 'deps: Bump oblt-cli version'
pipelineid: oblt-cli/version
automerge: false

path: .tool-versions
source_repository: oblt-cli

scm:
  enabled: false
  # user: v1v-bot
  # owner: v1v
  # repository: updatecli-demo
  # token: "xxx"
  # username: "v1v-bot"
  # branch: main
  # commitusingapi: false
  # force: true

pull_request:
  labels:
    - dependencies
