name: e2e

on:
  workflow_dispatch: ~

permissions:
  contents: read

jobs:
  compose:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - name: Get token
        id: get_token
        uses: elastic/oblt-actions/github/create-token@v1

      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: elastic/oblt-actions/updatecli/run@v1
        with:
          command: --experimental compose diff
          version-file: .tool-versions
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}

      - uses: elastic/oblt-actions/updatecli/run@v1
        with:
          command: --experimental compose apply
          version-file: .tool-versions
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
