name: Publish Policies

on:
  workflow_dispatch:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup updatecli
        uses: elastic/oblt-actions/updatecli/install@v1
        with:
          version-file: .tool-versions

      - name: Log in to the Container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: make release
