name: Validate Policies

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup updatecli
        uses: updatecli/updatecli-action@v2

      - name: Setup releasepost
        uses: updatecli/releasepost-action@108e7be5e43d1d1dc1177389a318d3630f6b01f1 # v0.4.0

      - name: Validate
        run: make test

      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        # Only run e2e tests from the main branch as we need some credentials
        # that we don't want to risk leaking from pullrequest opened by random contributors
        if: github.ref == 'refs/heads/main'
        id: generate_testing_token
        with:
          app_id: ${{ secrets.ELASTIC_OBSERVABILITY_APP_ID }}
          private_key: ${{ secrets.ELASTIC_OBSERVABILITY_APP_PEM }}

      - name: e2e tests
        # Only run e2e tests from the main branch as we need some credentials
        # that we don't want to risk leaking from pullrequest opened by random contributors
        if: github.ref == 'refs/heads/main'
        run: make e2e-test
        env:
          GITHUB_TOKEN: ${{ steps.generate_testing_token.outputs.token }}
          RELEASEPOST_GITHUB_TOKEN: ${{ steps.generate_testing_token.outputs.token }}
